### ISSUE TITLE
No need to unset $this->tasks

### ISSUE THREAD

**Issue by SOF3** [dktapps/LiveXYZ#2]
`$this->tasks` should be phantom like `$this` when the plugin is disabled. It is unnecessary to unset it explicitly. If the plugin's instance is kept, something else seriously wrong is happening.

**Comment by SOF3** [comment]
I know this was written a long time ago, but having this here is probably not good for your health ;)

**Comment by dktapps** [comment]
¯\_(ツ)_/¯ Will fix at a later date.

**Comment by CaitiffMCPE** [comment]
Which is just too difficult for his puny little mind to comprehend :)

**Comment by CaitiffMCPE** [comment]
That is it... All of you... keep going.... yes, yes... it won't be very long now.
