### ISSUE TITLE
coordinates obstruct health & hunger bar

### ISSUE THREAD

**Issue by Wizardon777** [dktapps/LiveXYZ#3]
Might be a good idea to change the location of the text.
![untitled](https://cloud.githubusercontent.com/assets/22551232/19005772/efadfdc2-8764-11e6-845c-27c86b987a29.jpg)

**Comment by dktapps** [comment]
That's a client issue. This has only become a problem in recent updates. If it isn't fixed in 0.16 I'll release an update to cater for it.

**Comment by Wizardon777** [comment]
ty!

**Comment by dktapps** [comment]
On branch `api3` I have added configuration options to allow switching between tips and popups. A popup should resolve your problem, but may be very laggy with a short refresh period. This will be closed when the api3 changes are merged to master.

**Comment by Yoyu666** [comment]
try move it too butom right :3
